name: CI/CD IAM Chatbot

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT }}
        # service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Docker Auth
      run: gcloud auth configure-docker

    - name: Build and Push Image
      run: |
        IMAGE=gcr.io/${{ secrets.GCP_PROJECT }}/iam-chatbot:${{ github.run_number }}
        docker build -t $IMAGE .
        docker push $IMAGE

    - name: Terraform Init & Apply (Staging)
      run: |
        terraform init
        terraform apply -auto-approve -var="env=staging"

    # - name: MS Teams Notify Success
    #   if: ${{ success() }}
    #   run: |
    #     curl -H 'Content-Type: application/json' \
    #     -d '{
    #       "@type": "MessageCard",
    #       "@context": "http://schema.org/extensions",
    #       "summary": "CI/CD Notification",
    #       "themeColor": "28A745",
    #       "title": "✅ CI/CD Pipeline Success",
    #       "text": "**IAM Chatbot** was successfully built and deployed to *Staging*.<br>Commit: `${{ github.sha }}`<br>Branch: `${{ github.ref_name }}`"
    #     }' \
    #     ${{ secrets.TEAMS_WEBHOOK }}

    - name: Terraform Apply (Production) [on Tag]
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        terraform init
        terraform workspace select prod || terraform workspace new prod
        terraform apply -auto-approve -var="env=prod"

    # - name: MS Teams Notify Production Deploy
    #   if: startsWith(github.ref, 'refs/tags/') && success()
    #   run: |
    #     curl -H 'Content-Type: application/json' \
    #     -d '{
    #       "@type": "MessageCard",
    #       "@context": "http://schema.org/extensions",
    #       "summary": "CI/CD Notification",
    #       "themeColor": "0078D4",
    #       "title": "🚀 Production Deployment Complete",
    #       "text": "**IAM Chatbot** was deployed to *Production* using tag `${{ github.ref_name }}`"
    #     }' \
    #     ${{ secrets.TEAMS_WEBHOOK }}

